spring.application.name=MafroshartElramyz
server.port=8086
spring.profiles.active=dev

# Updated to match Docker Compose defaults
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=admin
spring.datasource.password=mysecretpassword

# JPA settings
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true


jwt.secret=ElramyMafroshartJwtSecretKey2026VeryLongSecureKey123456
jwt.expiration=86400000

