spring.application.name=MafroshartElramyz
server.port=8086
spring.profiles.active=dev

## Updated to match Docker Compose defaults
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=admin
#spring.datasource.password=mysecretpassword

# JPA settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop


spring.datasource.url=jdbc:postgresql://ep-snowy-dawn-b52sx9hp-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WNbzKRis8C1v
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true


jwt.secret=ElramyMafroshartJwtSecretKey2026VeryLongSecureKey123456
jwt.expiration=86400000

